### ISSUE TITLE
Camera moves to below character when standing on certain terrain

### ISSUE THREAD

**Issue by ArchieT9988** [dgosling/RoR2-Samus#2] opened 2022-02-19 10:21 UTC
I've encountered this glitch recently, and have been finding whilst it doesn't actually effect the actual model's clipping, the camera seems to move as close to the ground as possible.

I've included three examples within screenshots

Example 1:
Lamp terrain pre-testing https://steamcommunity.com/sharedfiles/filedetails/?id=2758067105

Lamp terrain with glitch active https://steamcommunity.com/sharedfiles/filedetails/?id=2758066943

Example 2:
Tile Terrain pre-testing https://steamcommunity.com/sharedfiles/filedetails/?id=2758066721

Tile Terrain with glitch active https://steamcommunity.com/sharedfiles/filedetails/?id=2758066503

As another test, I wanted to see if it was only the camera effected, so I tried charging with the glitch active

The result of that https://steamcommunity.com/sharedfiles/filedetails/?id=2758066305

Example 3:
Titanic plains pre-testing https://steamcommunity.com/sharedfiles/filedetails/?id=2758076838

Titanic plains with glitch active https://steamcommunity.com/sharedfiles/filedetails/?id=2758077101

This is an issue that seems to only effect certain types of objects, as other objects, such as the rocks, rings, ETC. are not effected by it.

**Comment by dgosling** [comment] 2022-02-21 00:01
I have an idea of how I can fix this and am currently working on fixing it ATM.

**Comment by ArchieT9988** [comment] 2022-02-21 01:04
Alright, glad to know it's being worked on, good luck on the fix!

**Comment by dgosling** [comment] 2022-02-21 01:44
So, I'm pretty sure I found the fix for it, I'll double-check it and if the problem is gone, then after I finish the other fixes I'm working on, I'll release an update.

**Comment by dgosling** [comment] 2022-02-22 07:56
Should be fixed in commit c661b5ffd94c2b41a545fe88fb9ac546c58bb4d1.

**Closed as completed by dgosling** 2022-02-22 07:56 UTC
Labels: Moderate Bug
